version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter

    branches:
      only: /feature.+/

    steps:
      - checkout

      - run:
          name: Export Environment-Variables
          command: env > ~/.env

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run the application tests
          command: flutter test

      - run:
          name: Build the Android version
          command: flutter build apk

      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk
